### ISSUE TITLE
Add support for Postgres

### ISSUE THREAD

**Issue by iporollo** [monosidev/monosi#34]
## Problem
I want to use monosi with my Postgres data store

## Solution
Monosi needs to interpret Postgres configuration details and run on Postgres accordingly

## Requirements
1. Postgres instance
2. Refactor to support multiple formats for configurations
3. Add Postgres driver & dialect

**Comment by karen-pal** [comment]
Hello there. Congrats on your project, it seems very promising and useful!

I have interest on the PostgreSQL integration, so I'm here to give my two cents.

I was looking around the code to see how I could start with this task and I noticed the following:

I see the Driver template class is in an[ __init__ file](https://github.com/monosidev/monosi/blob/67c24c7cf9d645b2c3d80a83efbd3837e14b8c7f/monosi/drivers/__init__.py), instead of a Base class file which could be used for contributors to base their implementations on.

I see you have not followed that architecture consistently across the project. You broke that pattern in the [config directory](https://github.com/monosidev/monosi/tree/master/monosi/config), where you have a configuration.py file with base classes. 

I propose to use [Rasa's brokers](https://github.com/RasaHQ/rasa/tree/main/rasa/core/brokers) example as a guide:

> Rasa events can be managed by multiple configurable brokers (kafka, sql and rabbitmq's pika). This was handled with a broker.py file with a base class, and a module for each integration.

This same architectural pattern is followed for [Rasa's channels](https://github.com/RasaHQ/rasa/tree/main/rasa/core/channels). 

> Rasa provides integration with multiple channels (Whatsapp, Telegram, Socketio, etc). The base class is implemented in a channel.py file and the different channels inherit and override their base class implementation.

Rasa has proven to be a very successful open source project, currently being in production all over the world. Its code structure is remarkable and worth studying.

Let me know what you think.

**Comment by unkrich** [comment]
@karen-pal Totally agree with this - thanks a ton for your interest and the detailed response and links. We're still early in developing this project so I appreciate your patience and feedback. I'm definitely aware we need better support/architecture for building these integrations and it's a high priority.

I'm going to take a look at the links/code you posted and come back later today with a strategy - will ping you when I do (If you want to chat real-time / help out feel free to join the slack as well). There are a number of other reference architectures that I'm looking at as well.

Since this is a high priority, definitely want to make it possible for you to connect with PostgreSQL ASAP.

**Comment by unkrich** [comment]
Hi @karen-pal - I put in some work on the initial implementation here - I've also largely implemented PostgreSQL save one line of SQL at the moment as an example.

Would love your thoughts: https://github.com/monosidev/monosi/tree/refactor

I'll be happy to provide more details regarding the thought process on this soon (~1 day) or see you in slack, thanks!

**Comment by unkrich** [comment]
#42 #43 should wrap up the initial implementation on PostgreSQL

**Comment by karen-pal** [comment]
@unkrich Wow that was quick! 🤯 Just read the code refactor and that's exactly how I imagined it. What a great arch improvement!

I'll try setting it up and playing with it next week, as I'm going to have a couple of busy days. Will be joining the slack space for updates.

Congrats to the team for the fast development!

**Comment by unkrich** [comment]
@karen-pal You bet! Appreciate the push to get this through :) We're going to be making vast improvements like this just as fast - excited to have you around to keep us moving.

Feel free to reach out if you have any problems getting set up once you join Slack, always happy to help or jump on a call.
